### ISSUE TITLE
Cant use hostname

### ISSUE THREAD

**Issue by 112RG** [mh4x0f/botdr4g0n#2]
Hey man awesome tool but when I put in the hostname like this "test.local" it will not connect but if I do the ip it works. Can you not use hostnames like this? I cant use the ip because the network uses dhcp and the ip's are constantly changing. Any ideas?

**Comment by mh4x0f** [comment]
@112madgamer  I added support to resolve DNS, you need to do some tests, if not does work you can to do mapping  in the /etc/hosts file.
thanks for issue
